import {
  sequelize,
  User,
  Aset,
  PusatData,
  Riwayat,
  Notifikasi,
} from "./src/models/index.js";

const requireSeedPassword = (key) => {
  const value = process.env[key];
  if (!value) throw new Error(`${key} wajib diisi sebelum menjalankan seed`);
  return value;
};

async function seedAll() {
  try {
    // Drop and recreate all tables
    await sequelize.query('DROP TABLE IF EXISTS "notifikasi" CASCADE');
    await sequelize.query('DROP TABLE IF EXISTS "riwayat" CASCADE');
    await sequelize.query('DROP TABLE IF EXISTS "aset" CASCADE');
    await sequelize.query('DROP TABLE IF EXISTS "pusat_data" CASCADE');
    await sequelize.query('DROP TABLE IF EXISTS "users" CASCADE');
    await sequelize.query('DROP TYPE IF EXISTS "enum_users_role" CASCADE');
    await sequelize.query('DROP TYPE IF EXISTS "enum_aset_status" CASCADE');
    await sequelize.query(
      'DROP TYPE IF EXISTS "enum_aset_jenis_masalah" CASCADE',
    );
    await sequelize.query('DROP TYPE IF EXISTS "enum_riwayat_aksi" CASCADE');
    await sequelize.query('DROP TYPE IF EXISTS "enum_notifikasi_tipe" CASCADE');
    await sequelize.query(
      'DROP TYPE IF EXISTS "enum_notifikasi_kategori" CASCADE',
    );
    console.log("🗑️  Dropped all existing tables and enums");

    await sequelize.sync({ force: true });
    console.log("✅ Database synced with fresh schema");

    // ===== SEED USERS =====
    console.log("\n📦 Seeding users...");
    const users = [
      {
        username: "admin_bpka",
        password: requireSeedPassword("SEED_ADMIN_BPKA_PASSWORD"),
        email: "admin_bpka@bhumisatya.com",
        nama_lengkap: "Ir. Hadi Santoso, M.Si",
        role: "admin",
        jabatan: "Kepala Bidang Aset",
        instansi: "Unit Pengelola Aset",
        nip: "197805152005011003",
        status_aktif: true,
      },
      {
        username: "admin_bpn",
        password: requireSeedPassword("SEED_ADMIN_BPN_PASSWORD"),
        email: "admin_bpn@bhumisatya.com",
        nama_lengkap: "Drs. Agus Prasetyo, M.H",
        role: "admin",
        jabatan: "Kepala Seksi Penanganan Masalah",
        instansi: "Unit Pertanahan",
        nip: "198001082006041002",
        status_aktif: true,
      },
      {
        username: "bpka",
        password: requireSeedPassword("SEED_BPKA_PASSWORD"),
        email: "bpka@bhumisatya.com",
        nama_lengkap: "Siti Rahayu, S.E",
        role: "pengelola_aset",
        jabatan: "Operator Data Aset",
        instansi: "Unit Pengelola Aset",
        nip: "199003152018012001",
        status_aktif: true,
      },
      {
        username: "bpn_user",
        password: requireSeedPassword("SEED_BPN_PASSWORD"),
        email: "bpn@bhumisatya.com",
        nama_lengkap: "Rizky Firmansyah, S.H",
        role: "verifikator_aset",
        jabatan: "Verifikator Pertanahan",
        instansi: "Unit Pertanahan",
        nip: "199205202019031005",
        status_aktif: true,
      },
    ];

    const createdUsers = {};
    for (const userData of users) {
      const user = await User.create(userData);
      createdUsers[userData.username] = user.id_user;
      console.log(`  ✅ Created user: ${userData.username} (${userData.role})`);
    }

    // ===== SEED PUSAT DATA (BPKA) =====
    console.log("\n📦 Seeding Pusat Data (BPKA)...");
    const pusatDataItems = [
      {
        kode_barang: "01.01.11.04.01",
        nama_barang: "Tanah Kantor Kelurahan Area Operasional D",
        nibar: "NB-001-2020",
        luas: 1250.0,
        alamat:
          "Jl. Panglima Sudirman No. 10, Kel. Area Operasional D, Kec. Area Operasional D, Wilayah Operasional",
        nilai_perolehan: 2500000000,
        no_sertifikat: "HM-001/Area Operasional D",
        tanggal: "2020-03-15",
        opd: "Kelurahan Area Operasional D",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.02",
        nama_barang: "Tanah Puskesmas Subarea D7",
        nibar: "NB-002-2019",
        luas: 2100.5,
        alamat:
          "Jl. Dr. Wahidin No. 32, Kel. Subarea D7, Kec. Area Operasional C, Wilayah Operasional",
        nilai_perolehan: 4200000000,
        no_sertifikat: "HP-003/Subarea D7",
        tanggal: "2019-07-22",
        opd: "Unit Kesehatan",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.03",
        nama_barang: "Tanah SDN Subarea C4 1",
        nibar: "NB-003-2018",
        luas: 3500.0,
        alamat:
          "Jl. Veteran No. 45, Kel. Subarea C4, Kec. Area Operasional A, Wilayah Operasional",
        nilai_perolehan: 5250000000,
        no_sertifikat: "HP-012/Subarea C4",
        tanggal: "2018-01-10",
        opd: "Unit Pendidikan",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.04",
        nama_barang: "Tanah Lapangan Untung Suropati",
        nibar: "NB-004-2017",
        luas: 8500.0,
        alamat:
          "Jl. Untung Suropati, Kel. Subarea C1, Kec. Area Operasional C, Wilayah Operasional",
        nilai_perolehan: 12750000000,
        no_sertifikat: "HP-005/Subarea C1",
        tanggal: "2017-11-05",
        opd: "Dinas Pemuda dan Olahraga",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.05",
        nama_barang: "Tanah Pasar Subarea D7",
        nibar: "NB-005-2016",
        luas: 4200.0,
        alamat:
          "Jl. Pasar Subarea D7 No. 1, Kel. Subarea D7, Kec. Area Operasional C, Wilayah Operasional",
        nilai_perolehan: 8400000000,
        no_sertifikat: "HP-007/Subarea D7",
        tanggal: "2016-05-20",
        opd: "Dinas Perdagangan",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.06",
        nama_barang: "Tanah RSUD dr. R. Soedarsono",
        nibar: "NB-006-2015",
        luas: 15000.0,
        alamat:
          "Jl. Dr. Wahidin Sudirohusodo No. 4, Kel. Subarea D1, Kec. Area Operasional A, Wilayah Operasional",
        nilai_perolehan: 37500000000,
        no_sertifikat: "HP-015/Subarea D1",
        tanggal: "2015-09-12",
        opd: "RSUD dr. R. Soedarsono",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.07",
        nama_barang: "Tanah Kantor Kecamatan Area Operasional B",
        nibar: "NB-007-2021",
        luas: 1800.0,
        alamat:
          "Jl. Hayam Wuruk No. 8, Kel. Subarea B1, Kec. Area Operasional B, Wilayah Operasional",
        nilai_perolehan: 3600000000,
        no_sertifikat: "HP-020/Subarea B1",
        tanggal: "2021-02-28",
        opd: "Kecamatan Area Operasional B",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.08",
        nama_barang: "Tanah Terminal Subarea A2",
        nibar: "NB-008-2014",
        luas: 6000.0,
        alamat:
          "Jl. Ahmad Yani No. 100, Kel. Subarea A2, Kec. Area Operasional A, Wilayah Operasional",
        nilai_perolehan: 9000000000,
        no_sertifikat: "HP-025/Subarea A2",
        tanggal: "2014-06-30",
        opd: "Dinas Perhubungan",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.09",
        nama_barang: "Tanah TPA Subarea A2",
        nibar: "NB-009-2013",
        luas: 25000.0,
        alamat:
          "Jl. TPA Subarea A2, Kel. Subarea A2, Kec. Area Operasional A, Wilayah Operasional",
        nilai_perolehan: 12500000000,
        no_sertifikat: "HP-030/Subarea A2",
        tanggal: "2013-08-15",
        opd: "Dinas Lingkungan Hidup",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.10",
        nama_barang: "Tanah SMPN 1 Wilayah Operasional",
        nibar: "NB-010-2012",
        luas: 5600.0,
        alamat:
          "Jl. Kantor Pusat No. 22, Kel. Area Operasional D, Kec. Area Operasional D, Wilayah Operasional",
        nilai_perolehan: 11200000000,
        no_sertifikat: "HP-035/Area Operasional D",
        tanggal: "2012-04-10",
        opd: "Unit Pendidikan",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.11",
        nama_barang: "Tanah Gedung Administrasi Wilayah Operasional",
        nibar: "NB-011-2011",
        luas: 3200.0,
        alamat:
          "Jl. Pahlawan No. 50, Kel. Subarea C3, Kec. Area Operasional C, Wilayah Operasional",
        nilai_perolehan: 9600000000,
        no_sertifikat: "HP-040/Subarea C3",
        tanggal: "2011-10-20",
        opd: "Sekretariat Administrasi",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.12",
        nama_barang: "Tanah Balai Wilayah Operasional",
        nibar: "NB-012-2010",
        luas: 4800.0,
        alamat:
          "Jl. Alun-alun No. 1, Kel. Area Operasional D, Kec. Area Operasional D, Wilayah Operasional",
        nilai_perolehan: 24000000000,
        no_sertifikat: "HP-001/Area Operasional D",
        tanggal: "2010-01-05",
        opd: "Sekretariat Daerah",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.13",
        nama_barang: "Tanah Taman Wilayah Operasional",
        nibar: "NB-013-2022",
        luas: 7200.0,
        alamat:
          "Jl. Soekarno Hatta, Kel. Subarea D2, Kec. Area Operasional D, Wilayah Operasional",
        nilai_perolehan: 10800000000,
        no_sertifikat: "HP-045/Subarea D2",
        tanggal: "2022-06-01",
        opd: "Dinas Perumahan dan Kawasan Permukiman",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.14",
        nama_barang: "Tanah Kantor Dinas Sosial",
        nibar: "NB-014-2019",
        luas: 900.0,
        alamat:
          "Jl. WR. Supratman No. 15, Kel. Subarea C6, Kec. Area Operasional C, Wilayah Operasional",
        nilai_perolehan: 1800000000,
        no_sertifikat: "HP-050/Subarea C6",
        tanggal: "2019-12-10",
        opd: "Dinas Sosial",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.15",
        nama_barang: "Tanah Makam Umum Subarea A3",
        nibar: "NB-015-2008",
        luas: 32000.0,
        alamat: "Jl. Subarea A3, Kel. Subarea A3, Kec. Area Operasional C, Wilayah Operasional",
        nilai_perolehan: 6400000000,
        no_sertifikat: "HP-055/Subarea A3",
        tanggal: "2008-03-25",
        opd: "Dinas Lingkungan Hidup",
        pemegang: "Organisasi Pemilik Aset",
        created_by: createdUsers.bpka,
      },
    ];

    for (const item of pusatDataItems) {
      await PusatData.create(item);
    }
    console.log(`  ✅ Created ${pusatDataItems.length} Pusat Data items`);

    // ===== SEED ASET (BPN) =====
    console.log("\n📦 Seeding Aset (BPN)...");
    const asetItems = [
      {
        kode_aset: "AST-DEMO-001",
        nama_aset: "Tanah Kantor Kelurahan Area Operasional D",
        lokasi: "Jl. Panglima Sudirman No. 10, Area Operasional D",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 1250.0,
        status: "Aktif",
        jenis_aset: "Tanah Perkantoran",
        nilai_aset: 2500000000,
        tahun_perolehan: 2000,
        nomor_sertifikat: "HM-001/Area Operasional D/2000",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "2000-06-15",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional D",
        desa_kelurahan: "Area Operasional D",
        luas_lapangan: 1248.5,
        batas_utara: "Jl. Panglima Sudirman",
        batas_selatan: "Tanah Milik H. Ahmad",
        batas_timur: "Gang Mawar",
        batas_barat: "Kantor Pos",
        penggunaan_saat_ini: "Kantor Kelurahan",
        kode_bmd: "01.01.11.04.01",
        nilai_buku: 2500000000,
        nilai_njop: 2200000000,
        sk_penetapan: "SK Direksi No. 188/2000",
        opd_pengguna: "Kelurahan Area Operasional D",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "AST-DEMO-002",
        nama_aset: "Tanah Lapangan Untung Suropati",
        lokasi: "Jl. Untung Suropati, Subarea C1",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 8500.0,
        status: "Aktif",
        jenis_aset: "Tanah Fasilitas Umum",
        nilai_aset: 12750000000,
        tahun_perolehan: 1985,
        nomor_sertifikat: "HP-005/Subarea C1/1985",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1985-03-20",
        riwayat_perolehan: "Hibah",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional C",
        desa_kelurahan: "Subarea C1",
        luas_lapangan: 8497.0,
        batas_utara: "Jl. Untung Suropati",
        batas_selatan: "Perumahan Penduduk",
        batas_timur: "Jl. HOS Cokroaminoto",
        batas_barat: "SD Negeri Subarea C1 1",
        penggunaan_saat_ini: "Lapangan Olahraga",
        kode_bmd: "01.01.11.04.04",
        nilai_buku: 12750000000,
        nilai_njop: 11000000000,
        sk_penetapan: "SK Direksi No. 100/1985",
        opd_pengguna: "Dinas Pemuda dan Olahraga",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "AST-DEMO-003",
        nama_aset: "Tanah eks HGU Pihak Ketiga",
        lokasi: "Jl. Nusantara, Area Operasional B",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 12000.0,
        status: "Bermasalah",
        jenis_masalah: "Sengketa",
        jenis_aset: "Tanah Industri",
        nilai_aset: 18000000000,
        tahun_perolehan: 2010,
        nomor_sertifikat: "HGB-101/Area Operasional B/2010",
        status_sertifikat: "Dalam Proses",
        keterangan:
          "Sengketa batas dengan pihak swasta, proses mediasi berlangsung di BPN Provinsi",
        jenis_hak: "Hak Guna Bangunan",
        atas_nama: "Sengketa - Pihak Ketiga / Pengelola Aset",
        tanggal_sertifikat: "2010-08-20",
        riwayat_perolehan: "Tukar Menukar",
        status_hukum: "Dalam Sengketa",
        kecamatan: "Area Operasional B",
        desa_kelurahan: "Area Operasional B",
        luas_lapangan: 11850.0,
        batas_utara: "Sungai Gembong",
        batas_selatan: "Jl. Nusantara",
        batas_timur: "Tanah Pihak Ketiga",
        batas_barat: "Perumahan Area Operasional B Indah",
        penggunaan_saat_ini: "Lahan Kosong Bersengketa",
        kode_bmd: "01.01.11.04.20",
        nilai_buku: 18000000000,
        nilai_njop: 15600000000,
        sk_penetapan: "-",
        opd_pengguna: "-",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "AST-DEMO-004",
        nama_aset: "Tanah Pasar Subarea D7",
        lokasi: "Jl. Pasar Subarea D7 No. 1, Subarea D7",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 4200.0,
        status: "Aktif",
        jenis_aset: "Tanah Pasar",
        nilai_aset: 8400000000,
        tahun_perolehan: 1990,
        nomor_sertifikat: "HP-007/Subarea D7/1990",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1990-05-10",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional C",
        desa_kelurahan: "Subarea D7",
        luas_lapangan: 4195.0,
        batas_utara: "Jl. Pasar Subarea D7",
        batas_selatan: "Sungai",
        batas_timur: "Toko Milik Pak Slamet",
        batas_barat: "Gang Melati",
        penggunaan_saat_ini: "Pasar Tradisional",
        kode_bmd: "01.01.11.04.05",
        nilai_buku: 8400000000,
        nilai_njop: 7200000000,
        sk_penetapan: "SK Direksi No. 055/1990",
        opd_pengguna: "Dinas Perdagangan",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "AST-DEMO-005",
        nama_aset: "Tanah RSUD dr. R. Soedarsono",
        lokasi: "Jl. Dr. Wahidin Sudirohusodo No. 4, Subarea D1",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 15000.0,
        status: "Aktif",
        jenis_aset: "Tanah Kesehatan",
        nilai_aset: 37500000000,
        tahun_perolehan: 1975,
        nomor_sertifikat: "HP-015/Subarea D1/1975",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1975-12-01",
        riwayat_perolehan: "Hibah",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional A",
        desa_kelurahan: "Subarea D1",
        luas_lapangan: 14980.0,
        batas_utara: "Jl. Dr. Wahidin Sudirohusodo",
        batas_selatan: "Perumahan Penduduk",
        batas_timur: "Jl. Letjen S. Parman",
        batas_barat: "Sawah Milik Pak Darmo",
        penggunaan_saat_ini: "Rumah Sakit Umum Daerah",
        kode_bmd: "01.01.11.04.06",
        nilai_buku: 37500000000,
        nilai_njop: 32000000000,
        sk_penetapan: "SK Direksi No. 012/1975",
        opd_pengguna: "RSUD dr. R. Soedarsono",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "AST-DEMO-006",
        nama_aset: "Tanah Bekas Pabrik Gula Redjo Agung",
        lokasi: "Jl. Sultan Agung, Area Operasional C",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 22000.0,
        status: "Indikasi Bermasalah",
        jenis_aset: "Tanah Industri",
        nilai_aset: 55000000000,
        tahun_perolehan: 2005,
        nomor_sertifikat: "HGB-050/Area Operasional C/2005",
        status_sertifikat: "Dalam Proses",
        keterangan:
          "Indikasi tumpang tindih sertifikat dengan tanah masyarakat, perlu verifikasi lapangan",
        jenis_hak: "Hak Guna Bangunan",
        atas_nama: "Organisasi Pemilik Aset (Pengalihan dari Pemilik Sebelumnya)",
        tanggal_sertifikat: "2005-04-28",
        riwayat_perolehan: "Pengalihan",
        status_hukum: "Perlu Verifikasi",
        kecamatan: "Area Operasional C",
        desa_kelurahan: "Area Operasional C",
        luas_lapangan: 21500.0,
        batas_utara: "Jl. Sultan Agung",
        batas_selatan: "Sungai Gembong",
        batas_timur: "Perkampungan Warga RT 05",
        batas_barat: "Jl. Kartini",
        penggunaan_saat_ini: "Lahan Kosong (sebagian dipakai warga)",
        kode_bmd: "01.01.11.04.25",
        nilai_buku: 55000000000,
        nilai_njop: 48000000000,
        sk_penetapan: "SK Direksi No. 200/2005",
        opd_pengguna: "-",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "AST-DEMO-007",
        nama_aset: "Tanah SDN Subarea C4 1",
        lokasi: "Jl. Veteran No. 45, Subarea C4",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 3500.0,
        status: "Aktif",
        jenis_aset: "Tanah Pendidikan",
        nilai_aset: 5250000000,
        tahun_perolehan: 1980,
        nomor_sertifikat: "HP-012/Subarea C4/1980",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1980-07-15",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional A",
        desa_kelurahan: "Subarea C4",
        luas_lapangan: 3498.0,
        batas_utara: "Jl. Veteran",
        batas_selatan: "Makam Umum",
        batas_timur: "Rumah Warga",
        batas_barat: "Gang Merdeka",
        penggunaan_saat_ini: "Sekolah Dasar",
        kode_bmd: "01.01.11.04.03",
        nilai_buku: 5250000000,
        nilai_njop: 4500000000,
        sk_penetapan: "SK Direksi No. 075/1980",
        opd_pengguna: "Dinas Pendidikan",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "AST-DEMO-008",
        nama_aset: "Tanah Pelabuhan Rakyat Wilayah Operasional",
        lokasi: "Jl. Pelabuhan, Ngemplakrejo",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 18000.0,
        status: "Bermasalah",
        jenis_masalah: "Konflik",
        jenis_aset: "Tanah Pelabuhan",
        nilai_aset: 45000000000,
        tahun_perolehan: 1970,
        nomor_sertifikat: "HP-060/Ngemplakrejo/1970",
        status_sertifikat: "Dalam Proses",
        keterangan:
          "Konflik pemanfaatan lahan antara Pengelola Aset dengan nelayan dan pengelola tambak",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1970-01-10",
        riwayat_perolehan: "Hibah",
        status_hukum: "Dalam Konflik",
        kecamatan: "Area Operasional C",
        desa_kelurahan: "Ngemplakrejo",
        luas_lapangan: 17200.0,
        batas_utara: "Selat Madura",
        batas_selatan: "Jl. Pelabuhan",
        batas_timur: "Muara Sungai",
        batas_barat: "Tambak Ikan",
        penggunaan_saat_ini: "Pelabuhan Rakyat & Tambak",
        kode_bmd: "01.01.11.04.30",
        nilai_buku: 45000000000,
        nilai_njop: 39000000000,
        sk_penetapan: "SK Direksi No. 005/1970",
        opd_pengguna: "Dinas Perhubungan",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "AST-DEMO-009",
        nama_aset: "Tanah Taman Kota Depan Alun-alun",
        lokasi: "Jl. Alun-alun Utara, Area Operasional D",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 3800.0,
        status: "Aktif",
        jenis_aset: "Tanah Ruang Terbuka Hijau",
        nilai_aset: 7600000000,
        tahun_perolehan: 1960,
        nomor_sertifikat: "HP-002/Area Operasional D/1960",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1960-08-17",
        riwayat_perolehan: "Warisan Kolonial",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional D",
        desa_kelurahan: "Area Operasional D",
        luas_lapangan: 3795.0,
        batas_utara: "Jl. Alun-alun Utara",
        batas_selatan: "Masjid Agung Al-Anwar",
        batas_timur: "Jl. Alun-alun Timur",
        batas_barat: "Jl. Alun-alun Barat",
        penggunaan_saat_ini: "Taman Kota & RTH",
        kode_bmd: "01.01.11.04.35",
        nilai_buku: 7600000000,
        nilai_njop: 6500000000,
        sk_penetapan: "SK Direksi No. 001/1960",
        opd_pengguna: "Dinas Perumahan dan Kawasan Permukiman",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "AST-DEMO-010",
        nama_aset: "Tanah Kawasan Industri Subarea A2",
        lokasi: "Jl. Raya Subarea A2, Subarea A2",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 35000.0,
        status: "Diblokir",
        jenis_masalah: "Berperkara",
        jenis_aset: "Tanah Industri",
        nilai_aset: 70000000000,
        tahun_perolehan: 2015,
        nomor_sertifikat: "HGB-200/Subarea A2/2015",
        status_sertifikat: "Diblokir",
        keterangan:
          "Tanah diblokir karena perkara perdata di Pengadilan Negeri No. 45/PDT/2023/PN.DEMO",
        jenis_hak: "Hak Guna Bangunan",
        atas_nama: "Dalam Perkara - Pengelola Aset vs Developer",
        tanggal_sertifikat: "2015-11-30",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Berperkara di Pengadilan",
        kecamatan: "Area Operasional A",
        desa_kelurahan: "Subarea A2",
        luas_lapangan: 34500.0,
        batas_utara: "Jl. Raya Subarea A2",
        batas_selatan: "Lahan Pertanian",
        batas_timur: "Sungai Kedung Larangan",
        batas_barat: "Perumahan Subarea A2",
        penggunaan_saat_ini: "Diblokir - Tidak Dapat Digunakan",
        kode_bmd: "01.01.11.04.40",
        nilai_buku: 70000000000,
        nilai_njop: 60000000000,
        sk_penetapan: "SK Direksi No. 300/2015 (Diblokir)",
        opd_pengguna: "-",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "AST-DEMO-011",
        nama_aset: "Tanah Balai Wilayah Operasional",
        lokasi: "Jl. Alun-alun No. 1, Area Operasional D",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 4800.0,
        status: "Aktif",
        jenis_aset: "Tanah Perkantoran",
        nilai_aset: 24000000000,
        tahun_perolehan: 1950,
        nomor_sertifikat: "HP-001/Area Operasional D/1950",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1950-01-01",
        riwayat_perolehan: "Warisan Kolonial",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional D",
        desa_kelurahan: "Area Operasional D",
        luas_lapangan: 4798.0,
        batas_utara: "Jl. Alun-alun",
        batas_selatan: "Jl. Veteran",
        batas_timur: "Kantor Administrasi",
        batas_barat: "Pendopo Direksi",
        penggunaan_saat_ini: "Kantor Direksi Wilayah Operasional",
        kode_bmd: "01.01.11.04.12",
        nilai_buku: 24000000000,
        nilai_njop: 20000000000,
        sk_penetapan: "SK Direksi No. 001/1950",
        opd_pengguna: "Sekretariat Daerah",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "AST-DEMO-012",
        nama_aset: "Tanah Puskesmas Subarea D7",
        lokasi: "Jl. Dr. Wahidin No. 32, Subarea D7",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 2100.5,
        status: "Aktif",
        jenis_aset: "Tanah Kesehatan",
        nilai_aset: 4200000000,
        tahun_perolehan: 1995,
        nomor_sertifikat: "HP-003/Subarea D7/1995",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1995-09-01",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional C",
        desa_kelurahan: "Subarea D7",
        luas_lapangan: 2098.0,
        batas_utara: "Jl. Dr. Wahidin",
        batas_selatan: "Rumah Warga",
        batas_timur: "Gang Kenari",
        batas_barat: "Apotek Sehat",
        penggunaan_saat_ini: "Puskesmas",
        kode_bmd: "01.01.11.04.02",
        nilai_buku: 4200000000,
        nilai_njop: 3800000000,
        sk_penetapan: "SK Direksi No. 090/1995",
        opd_pengguna: "Dinas Kesehatan",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "AST-DEMO-013",
        nama_aset: "Tanah Gedung Administrasi Wilayah Operasional",
        lokasi: "Jl. Pahlawan No. 50, Subarea C3",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 3200.0,
        status: "Aktif",
        jenis_aset: "Tanah Perkantoran",
        nilai_aset: 9600000000,
        tahun_perolehan: 1988,
        nomor_sertifikat: "HP-040/Subarea C3/1988",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1988-04-21",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional C",
        desa_kelurahan: "Subarea C3",
        luas_lapangan: 3198.0,
        batas_utara: "Jl. Pahlawan",
        batas_selatan: "Perumahan Subarea C3",
        batas_timur: "Taman Mini",
        batas_barat: "Bank Jatim",
        penggunaan_saat_ini: "Gedung Administrasi",
        kode_bmd: "01.01.11.04.11",
        nilai_buku: 9600000000,
        nilai_njop: 8400000000,
        sk_penetapan: "SK Direksi No. 045/1988",
        opd_pengguna: "Sekretariat Administrasi",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "AST-DEMO-014",
        nama_aset: "Tanah Makam Umum Subarea A3",
        lokasi: "Jl. Subarea A3, Subarea A3",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 32000.0,
        status: "Aktif",
        jenis_aset: "Tanah Makam",
        nilai_aset: 6400000000,
        tahun_perolehan: 1955,
        nomor_sertifikat: "HP-055/Subarea A3/1955",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1955-06-01",
        riwayat_perolehan: "Warisan Kolonial",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional C",
        desa_kelurahan: "Subarea A3",
        luas_lapangan: 31800.0,
        batas_utara: "Jl. Subarea A3",
        batas_selatan: "Sawah",
        batas_timur: "Perumahan Warga",
        batas_barat: "Jl. Sunan Ampel",
        penggunaan_saat_ini: "Makam Umum",
        kode_bmd: "01.01.11.04.15",
        nilai_buku: 6400000000,
        nilai_njop: 5500000000,
        sk_penetapan: "SK Direksi No. 003/1955",
        opd_pengguna: "Dinas Lingkungan Hidup",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "AST-DEMO-015",
        nama_aset: "Tanah Terminal Subarea A2",
        lokasi: "Jl. Ahmad Yani No. 100, Subarea A2",
        koordinat_lat: null,
        koordinat_long: null,
        luas: 6000.0,
        status: "Aktif",
        jenis_aset: "Tanah Transportasi",
        nilai_aset: 9000000000,
        tahun_perolehan: 1992,
        nomor_sertifikat: "HP-025/Subarea A2/1992",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Organisasi Pemilik Aset",
        tanggal_sertifikat: "1992-10-10",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Area Operasional A",
        desa_kelurahan: "Subarea A2",
        luas_lapangan: 5990.0,
        batas_utara: "Jl. Ahmad Yani",
        batas_selatan: "Lahan Pertanian",
        batas_timur: "Bengkel Jaya Motor",
        batas_barat: "Rumah Warga RT 03",
        penggunaan_saat_ini: "Terminal Bus Kota",
        kode_bmd: "01.01.11.04.08",
        nilai_buku: 9000000000,
        nilai_njop: 7800000000,
        sk_penetapan: "SK Direksi No. 110/1992",
        opd_pengguna: "Dinas Perhubungan",
        created_by: createdUsers.admin_bpn,
      },
    ];

    for (const item of asetItems) {
      await Aset.create(item);
    }
    console.log(`  ✅ Created ${asetItems.length} Aset items`);

    // ===== SUMMARY =====
    console.log("\n" + "=".repeat(60));
    console.log("✅ LOCAL DATABASE SEEDED SUCCESSFULLY!");
    console.log("=".repeat(60));
    console.log(`\n📊 Summary:`);
    console.log(`   Users:       ${users.length}`);
    console.log(`   Pusat Data:  ${pusatDataItems.length} (BPKA)`);
    console.log(`   Aset:        ${asetItems.length} (BPN)`);
    console.log(`\n🔑 Credentials:`);
    console.log("   Password akun seed dibaca dari environment.");
    console.log("=".repeat(60));

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error.message);
    console.error(error);
    process.exit(1);
  }
}

seedAll();
